ranking <- read.csv("Output/RefugiaRanking.csv", header = TRUE)
ranking2 <- cbind(ranking$ID, ranking[ , grepl("score", names(ranking))])
n <- names(ranking2)

lines0 <- c("Version: 2.0",
            "",
            "#########################",
            "# Alternatives Section",
            "#",
            "",
            "Alternatives: &alternatives"
)

lines1 <- sapply(1:length(ranking$ID), function(x)
  c(paste0("  ",ranking2[x,1],":"),
    paste0("    ", n[2], ": ", ranking2[x, 2]),
    paste0("    ", n[3], ": ", ranking2[x, 3]),
    paste0("    ", n[4], ": ", ranking2[x, 4]),
    paste0("    ", n[5], ": ", ranking2[x, 5]),
    paste0("    ", n[6], ": ", ranking2[x, 6]))
)

lines2 <- c("",
            "#",
            "# End of Alternatives Section",
            "#####################################",
            "",
            "#####################################",
            "# Goal Section",
            "#",
            "",
            "",
            "Goal:",
            "  name: Most important refugia",
            "  description : >",
            "  author: AJM",
            "  preferences:",
            "    pairwise:",
            "      - [score.building, score.habitat, 1/9]",
            "      - [score.building, score.invasive, 1/3]",
            "      - [score.building, score.isol, 1/5]",
            "      - [score.building, score.RelAbundance, 1/9]",
            "      - [score.habitat, score.invasive, 5]",
            "      - [score.habitat, score.isol, 3]",
            "      - [score.habitat, score.RelAbundance, 5]",
            "      - [score.invasive, score.isol, 1/3]",
            "      - [score.invasive, score.RelAbundance, 3]",
            "      - [score.isol, score.RelAbundance, 1]",
            "    children:",
            "      score.building:",
            "        preferences:",
            "          pairwiseFunction:",
            "            PrefBuilding <- function(a1, a2){",
            "              if(a1$score.building < a2$score.building) return(1/PrefBuilding(a2,a1))",
            "              ratio <- a1$score.building / a2$score.building",
            "              if(is.na(ratio) return (1)",
            "              if(ratio < 1.11 return (1)",
            "              if(ratio < 1.22 return (2)",
            "              if(ratio < 1.33 return (3)",
            "              if(ratio < 1.44 return (4)",
            "              if(ratio < 1.55 return (5)",
            "              if(ratio < 1.66 return (6)",
            "              if(ratio < 1.77 return (7)",
            "              if(ratio < 1.88 return (8)",
            "              if(ratio < 2 return (9)",
            "            }",
            "        children: *alternatives",
            "      score.habitat:",
            "        preferences:",
            "          pairwiseFunction:",
            "            PrefHabitat <- function(a1, a2){",
            "              if(a1$score.habitat < a2$score.habitat) return(1/PrefHabitat(a2,a1))",
            "              ratio <- a1$score.habitat / a2$score.habitat",
            "              if(is.na(ratio) return (1)",
            "              if(ratio < 1.11 return (1)",
            "              if(ratio < 1.22 return (2)",
            "              if(ratio < 1.33 return (3)",
            "              if(ratio < 1.44 return (4)",
            "              if(ratio < 1.55 return (5)",
            "              if(ratio < 1.66 return (6)",
            "              if(ratio < 1.77 return (7)",
            "              if(ratio < 1.88 return (8)",
            "              if(ratio < 2 return (9)",
            "            }",
            "        children: *alternatives",
            "      score.invasive:",
            "        preferences:",
            "          pairwiseFunction:",
            "            PrefInvasive <- function(a1, a2){",
            "              if(a1$score.invasive < a2$score.invasive) return(1/PrefInvasive(a2,a1))",
            "              ratio <- a1$score.invasive / a2$score.invasive",
            "              if(is.na(ratio) return (1)",
            "              if(ratio < 1.11 return (1)",
            "              if(ratio < 1.22 return (2)",
            "              if(ratio < 1.33 return (3)",
            "              if(ratio < 1.44 return (4)",
            "              if(ratio < 1.55 return (5)",
            "              if(ratio < 1.66 return (6)",
            "              if(ratio < 1.77 return (7)",
            "              if(ratio < 1.88 return (8)",
            "              if(ratio < 2 return (9)",
            "            }",
            "        children: *alternatives",
            "      score.isol:",
            "        preferences:",
            "          pairwiseFunction:",
            "            PrefIsol <- function(a1, a2){",
            "              if(a1$score.isol < a2$score.isol) return(1/PrefIsol(a2,a1))",
            "              ratio <- a1$score.isol / a2$score.isol",
            "              if(is.na(ratio) return (1)",
            "              if(ratio < 1.11 return (1)",
            "              if(ratio < 1.22 return (2)",
            "              if(ratio < 1.33 return (3)",
            "              if(ratio < 1.44 return (4)",
            "              if(ratio < 1.55 return (5)",
            "              if(ratio < 1.66 return (6)",
            "              if(ratio < 1.77 return (7)",
            "              if(ratio < 1.88 return (8)",
            "              if(ratio < 2 return (9)",
            "            }",
            "        children: *alternatives",
            "      score.RelAbundance:",
            "        preferences:",
            "          pairwiseFunction:",
            "            PrefRelAbundance <- function(a1, a2){",
            "              if(a1$score.RelAbundance < a2$score.RelAbundance) return(1/PrefRelAbundance(a2,a1))",
            "              ratio <- a1$score.RelAbundance / a2$score.RelAbundance",
            "              if(is.na(ratio) return (1)",
            "              if(ratio < 1.11 return (1)",
            "              if(ratio < 1.22 return (2)",
            "              if(ratio < 1.33 return (3)",
            "              if(ratio < 1.44 return (4)",
            "              if(ratio < 1.55 return (5)",
            "              if(ratio < 1.66 return (6)",
            "              if(ratio < 1.77 return (7)",
            "              if(ratio < 1.88 return (8)",
            "              if(ratio < 2 return (9)",
            "            }",
            "        children: *alternatives",
            "",
            "#",
            "# End of Goal Section",
            "#####################################"
)
            

test1 <- file("test1.txt")
writeLines(c(lines0,lines1, lines2), test1)
close(test1)



########################## testing ###############################

c(
"  preferences:",
"    pairwise:",
"      - [score.building, score.habitat, 1/9]",
"      - [score.building, score.invasive, 1/3]",
"      - [score.building, score.isol, 1/5]",
"      - [score.building, score.RelAbundance, 1/9]",
"      - [score.habitat, score.invasive, 5]",
"      - [score.habitat, score.isol, 3]",
"      - [score.habitat, score.RelAbundance, 5]",
"      - [score.invasive, score.isol, 1/3]",
"      - [score.invasive, score.RelAbundance, 3]",
"      - [score.isol, score.RelAbundance, 1]",
"  children:",
"    score.building:",
"      preferences:",
"        pairwiseFunction:",
"          PrefBuilding <- function(a1, a2){",
"            if(a1$score.building < a2$score.building) return(1/PrefBuilding(a2,a1))",
"            ratio <- a1$score.building / a2$score.building",
"            if(is.na(ratio) return (1)",
"            if(ratio < 1.11 return (1)",
"            if(ratio < 1.22 return (1)",
"            if(ratio < 1.33 return (1)",
"            if(ratio < 1.44 return (1)",
"            if(ratio < 1.55 return (1)",
"            if(ratio < 1.66 return (1)",
"            if(ratio < 1.77 return (1)",
"            if(ratio < 1.88 return (1)",
"            if(ratio < return (1)",
"          }",
"      children: *alternatives",
"    score.habitat:",
"      preferences:",
"        pairwiseFunction:",
"          PrefHabitat <- function(a1, a2){",
"            if(a1$score.habitat < a2$score.habitat) return(1/PrefHabitat(a2,a1))",
"            ratio <- a1$score.habitat / a2$score.habitat",
"            if(is.na(ratio) return (1)",
"            if(ratio < 1.11 return (1)",
"            if(ratio < 1.22 return (1)",
"            if(ratio < 1.33 return (1)",
"            if(ratio < 1.44 return (1)",
"            if(ratio < 1.55 return (1)",
"            if(ratio < 1.66 return (1)",
"            if(ratio < 1.77 return (1)",
"            if(ratio < 1.88 return (1)",
"            if(ratio < return (1)",
"          }",
"      children: *alternatives",
"    score.invasive:",
"      preferences:",
"        pairwiseFunction:",
"          PrefInvasive <- function(a1, a2){",
"            if(a1$score.invasive < a2$score.invasive) return(1/PrefInvasive(a2,a1))",
"            ratio <- a1$score.invasive / a2$score.invasive",
"            if(is.na(ratio) return (1)",
"            if(ratio < 1.11 return (1)",
"            if(ratio < 1.22 return (1)",
"            if(ratio < 1.33 return (1)",
"            if(ratio < 1.44 return (1)",
"            if(ratio < 1.55 return (1)",
"            if(ratio < 1.66 return (1)",
"            if(ratio < 1.77 return (1)",
"            if(ratio < 1.88 return (1)",
"            if(ratio < return (1)",
"          }",
"      children: *alternatives",
"    score.isol:",
"      preferences:",
"        pairwiseFunction:",
"          PrefIsol <- function(a1, a2){",
"            if(a1$score.isol < a2$score.isol) return(1/PrefIsol(a2,a1))",
"            ratio <- a1$score.isol / a2$score.isol",
"            if(is.na(ratio) return (1)",
"            if(ratio < 1.11 return (1)",
"            if(ratio < 1.22 return (1)",
"            if(ratio < 1.33 return (1)",
"            if(ratio < 1.44 return (1)",
"            if(ratio < 1.55 return (1)",
"            if(ratio < 1.66 return (1)",
"            if(ratio < 1.77 return (1)",
"            if(ratio < 1.88 return (1)",
"            if(ratio < return (1)",
"          }",
"      children: *alternatives",
"    score.RelAbundance:",
"      preferences:",
"        pairwiseFunction:",
"          PrefRelAbundance <- function(a1, a2){",
"            if(a1$score.RelAbundance < a2$score.RelAbundance) return(1/PrefRelAbundance(a2,a1))",
"            ratio <- a1$score.RelAbundance / a2$score.RelAbundance",
"            if(is.na(ratio) return (1)",
"            if(ratio < 1.11 return (1)",
"            if(ratio < 1.22 return (1)",
"            if(ratio < 1.33 return (1)",
"            if(ratio < 1.44 return (1)",
"            if(ratio < 1.55 return (1)",
"            if(ratio < 1.66 return (1)",
"            if(ratio < 1.77 return (1)",
"            if(ratio < 1.88 return (1)",
"            if(ratio < return (1)",
"          }",
"      children: *alternatives"
)

